# Generated by Django 2.0.2 on 2018-03-22 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=40)),
                ('score', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answerer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=128)),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaseGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionWithGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word2description.Description')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=1024)),
                ('complainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word2description.Description')),
            ],
        ),
        migrations.CreateModel(
            name='Questioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=128)),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40)),
                ('pos', models.IntegerField(choices=[(0, 'Noun'), (1, 'Verb'), (2, 'Adjective'), (3, 'Adverb')])),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('basegame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='word2description.BaseGame')),
                ('questioner', models.CharField(default='', max_length=128)),
                ('answerer', models.CharField(default='', max_length=128)),
            ],
            bases=('word2description.basegame',),
        ),
        migrations.CreateModel(
            name='GamePool',
            fields=[
                ('basegame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='word2description.BaseGame')),
                ('label', models.CharField(max_length=40)),
            ],
            bases=('word2description.basegame',),
        ),
        migrations.AddField(
            model_name='descriptionwithgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word2description.BaseGame'),
        ),
        migrations.AddField(
            model_name='description',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word2description.Word'),
        ),
        migrations.AddField(
            model_name='description',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word2description.DescriptionWithGame'),
        ),
        migrations.AddField(
            model_name='answer',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questioner',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word2description.GamePool'),
        ),
        migrations.AddField(
            model_name='answerer',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word2description.GamePool'),
        ),
    ]
